name:                servant-demo
version:             0.1.0.0
github:              "chkl/servant-demo"
license:             BSD3
author:              "Christian Klinger"
copyright:           "2020 Christian Klinger"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chkl/servant-demo#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- lens
- rio
- scotty
- servant
- servant-client
- servant-server
- stm
- tasty
- tasty-wai
- text
- uuid
- warp
- wreq
- wai
- http-types

library:
  source-dirs: src

ghc-options: -Wincomplete-patterns  -Wincomplete-uni-patterns -Wincomplete-record-updates -Wno-partial-type-signatures -Wno-missing-home-modules -Wno-name-shadowing -Wno-type-defaults -Werror 

executables:
  servant-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-demo

tests:
  servant-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-demo
